#!/usr/bin/env node
/**
 * scripts/deploy.js
 *
 * The "npx convex deploy" equivalent. One command pushes your local
 * schema, RLS policies, triggers, and seed-free migrations to a
 * remote Supabase project.
 *
 * What it does:
 *   1. Checks you're linked to a remote project (if not, prompts to link).
 *   2. Diffs local migrations vs remote — bails on drift.
 *   3. Runs the RLS guard (no public table without RLS).
 *   4. Pushes migrations.
 *   5. Regenerates types from the *remote* schema so your local
 *      types.ts always matches what's deployed.
 *
 * Usage:
 *   npm run deploy                   # uses the linked project
 *   npm run deploy -- --project-ref abcdefg
 */

const { execSync, spawnSync } = require('child_process');
const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');

const c = {
  cyan: (s) => `\x1b[36m${s}\x1b[0m`,
  green: (s) => `\x1b[32m${s}\x1b[0m`,
  yellow: (s) => `\x1b[33m${s}\x1b[0m`,
  red: (s) => `\x1b[31m${s}\x1b[0m`,
  bold: (s) => `\x1b[1m${s}\x1b[0m`,
  dim: (s) => `\x1b[2m${s}\x1b[0m`,
};
const log = (m) => console.log(`${c.cyan('→')} ${m}`);
const ok = (m) => console.log(`${c.green('✓')} ${m}`);
const warn = (m) => console.log(`${c.yellow('!')} ${m}`);
const die = (m) => {
  console.error(`${c.red('✗')} ${m}`);
  process.exit(1);
};

// ─── parse args ─────────────────────────────────────────────────────
const args = process.argv.slice(2);
const refIdx = args.indexOf('--project-ref');
const projectRef = refIdx >= 0 ? args[refIdx + 1] : null;

// ─── 1. Ensure linked ───────────────────────────────────────────────
function ensureLinked() {
  const linkedFile = path.join(ROOT, 'supabase', '.temp', 'project-ref');
  const isLinked = fs.existsSync(linkedFile);

  if (projectRef) {
    log(`Linking to project ${projectRef}…`);
    const r = spawnSync('npx', ['supabase', 'link', '--project-ref', projectRef], {
      cwd: ROOT,
      stdio: 'inherit',
    });
    if (r.status !== 0) die('Link failed.');
    ok('Linked');
    return;
  }

  if (!isLinked) {
    die(
      'No remote project linked.\n' +
        '  1. Create one at https://supabase.com/dashboard (free tier is fine).\n' +
        '  2. Run: npm run deploy -- --project-ref <your-project-ref>\n' +
        '  Your project-ref is the slug in the dashboard URL.',
    );
  }

  const ref = fs.readFileSync(linkedFile, 'utf8').trim();
  ok(`Linked to ${ref}`);
}

// ─── 2. RLS guard (against the LOCAL stack, which has the
// migrations we're about to push applied) ─────────────────────────
function rlsGuard() {
  log('Verifying RLS is enabled on every public table…');
  const r = spawnSync('node', ['scripts/check-rls.js'], {
    cwd: ROOT,
    stdio: 'inherit',
  });
  if (r.status !== 0) die('RLS guard failed. Fix before deploying.');
}

// ─── 3. Push migrations ─────────────────────────────────────────────
function pushMigrations() {
  log('Pushing migrations to remote…');
  const r = spawnSync('npx', ['supabase', 'db', 'push'], {
    cwd: ROOT,
    stdio: 'inherit',
  });
  if (r.status !== 0) {
    die(
      'Push failed. Common causes:\n' +
        '  - Schema drift: someone edited the remote DB via the dashboard.\n' +
        "    Run 'npx supabase db pull' to capture it as a migration first.\n" +
        '  - A migration was edited after being applied — never edit, always add new.',
    );
  }
  ok('Migrations pushed');
}

// ─── 4. Regenerate types from remote ────────────────────────────────
function generateTypesFromRemote() {
  log('Generating types from remote schema…');
  try {
    const types = execSync('npx supabase gen types typescript --linked', {
      cwd: ROOT,
      encoding: 'utf8',
    });
    const header =
      '// supabase/types.ts\n' +
      '//\n' +
      '// GENERATED FILE — do not edit by hand.\n' +
      '// Regenerated by: npm run deploy\n' +
      '// Source: remote linked project\n\n';
    fs.writeFileSync(path.join(ROOT, 'supabase', 'types.ts'), header + types);
    ok('Types regenerated from remote');
  } catch {
    warn('Could not regenerate types from remote — falling back to local.');
    spawnSync('node', ['scripts/gen-types.js'], { cwd: ROOT, stdio: 'inherit' });
  }
}

// ─── main ───────────────────────────────────────────────────────────
function main() {
  console.log(c.bold('\nBNA Supabase — deploy\n'));
  ensureLinked();
  rlsGuard();
  pushMigrations();
  generateTypesFromRemote();
  console.log('');
  ok('Deploy complete.');
  console.log(
    c.dim(
      '  Update your .env.production (or EAS secrets) with the remote\n' +
        '  EXPO_PUBLIC_SUPABASE_URL and EXPO_PUBLIC_SUPABASE_KEY before building.',
    ),
  );
}

main();
